name: Build for Linux

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RESULT_DIRECTORY: result
      EXECUTABLE_FILE_NAME: bevy_jam
    runs-on: ubuntu-latest
    outputs: 
      binaries: result
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    
    - name: Cache
      uses: actions/cache@v2
      with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ env.EXECUTABLE_FILE_NAME }}-${{ hashFiles('**/Cargo.toml') }}
          
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install Dependencies
      run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    
    - name: Build
      run: cargo build --release
      
    - name: Create result directory
      run: mkdir ${{ env.RESULT_DIRECTORY }} -p -v
      
    - name: Collect binaries to result directory
      run: mv -f "target/release/${{ env.EXECUTABLE_FILE_NAME }}" "target/release/${{ env.EXECUTABLE_FILE_NAME }}.d" "assets" "${{ env.RESULT_DIRECTORY }}"
    
